"""add saved_configurations table

Revision ID: f2fb2296d1c6
Revises: d811b3f62d69
Create Date: 2026-07-23 13:56:10.760183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2fb2296d1c6'
down_revision: Union[str, None] = 'd811b3f62d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('selection_mode', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('lens_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('validated_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocking_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['catalog.drivers.id'], ),
    sa.ForeignKeyConstraint(['lens_id'], ['catalog.lenses.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['catalog.led_modules.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['consulting.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='consulting'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_configurations', schema='consulting')
    # ### end Alembic commands ###
